### ISSUE TITLE
Thold Wizard enables Cacti poller to remove newly created thresholds

### ISSUE THREAD

**Issue by swissalpsboy** [Cacti/plugin_thold#353] opened 2019-07-22 13:53 UTC
Hello
Thold-slider deletes newly created Threshold's.
If a new threshold is created, it is visible after a click on the slider "thold" and stored in the DB under "thold_data". Everything I.O.

If you only click on the slider "thold" one more time, the newly created threshold will be deleted. This also applies to the DB.
Threshold's from earlier versions remain unchanged.

For testing I deleted the old DB entries and removed the old plugin completely and installed the new version. Same result...

Cacti Version: 1.2.5
Thold Version: 1.3.2

Translated with www.DeepL.com/Translator

**Comment by netniV** [comment] 2019-07-22 14:59
Unfortunately, the translation leaves a lot to be desired.  Which button called 'thold' are you using? Top menu, console -> management -> thresholds, console -> templates -> thresholds?

**Comment by swissalpsboy** [comment] 2019-07-23 07:27
Hi netniV, 
Thanks for the quick answer.
Apology for the translation. Made some screenshots. Does that help?
[thold1.pdf](https://github.com/Cacti/plugin_thold/files/3420723/thold1.pdf)

**Comment by netniV** [comment] 2019-07-23 23:04
if you do `select count(*) from thold_data` what do you get?

**Comment by swissalpsboy** [comment] 2019-07-24 03:23
```
`MariaDB` [cacti]> select count(*) from thold_data;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

**Comment by netniV** [comment] 2019-07-24 07:11
Hmm, that is odd... it's almost like it thinks a delete action has been run.

**Comment by cigamit** [comment] 2019-07-25 01:44
I think this is a timing issue.  We clear out thold's that have a local_data_id set to 0 every polling cycle.  Not sure exactly how it's happening though.

**Comment by cigamit** [comment] 2019-07-25 01:47
Also, how were you able to select 'None' for device?

**Comment by cigamit** [comment] 2019-07-25 01:49
Okay, I was able to reproduce.  It looks like you selected 'device' == Any, and then saved, and the the Data Collector comes along and wipes it out as an invalid thold since it is not associated with a device.

**Comment by cigamit** [comment] 2019-07-25 02:02
This should be resolved in the develop branch.

**Closed as completed** 2020-03-01 18:38 UTC
Labels: bug, resolved
