### ISSUE TITLE
All thresholds gone after upgrade of the plugin

### ISSUE THREAD

**Issue by gdsotirov** [Cacti/plugin_thold#475] opened 2020-12-09 09:07 UTC
**Describe the bug**
After upgrade of the thold plugin all my thresholds are gone (both templates and on devices).

**To Reproduce**
1. Go to `plugins` directory of your Cacti installation;
2. Download new plugin from GitHub;
3. Remove old plugin directory `thold`;
4. Extract new version to `thold` directory;
5. Go to Console -> Plugins;
6. **Disable and uninstall old plugin**;
7. Install and enable new plugin;

**Expected behavior**
The new plugin is installed and all existing thresholds are preserved.

**Plugin (please complete the following information):**
 - Version: 1.5.2
 - Source: GitHub
 - Identifier: https://github.com/Cacti/plugin_thold/releases/tag/v1.5.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 83.0

**Additional context**
I guess the problem was that I disabled and **uninstalled** the plugin, but should this really delete all my user data that I carefully crafted in the past years!? This is definitely something that shouldn't happen silently. What is the correct procedure for upgrading Cacti plugins as I wasn't able to find it?

**Comment by TheWitness** [comment] 2020-12-09 11:07
Hopefully you had a backup.  The uninstaller does warn, but many even like me don't read these things.

**Comment by gdsotirov** [comment] 2020-12-09 11:59
Yes, hopefully I had database backup, but data restoration was _not_ that straight forward, because of structural differences between the old and new tables. Anyway, I really do not remember any warning when uninstalling the plugin, but my point is that removing a plugin should not remove its data in the database or at least this should be an option (which is off by default).

**Comment by TheWitness** [comment] 2020-12-09 12:02
Just restore the thold tables, then update the plugin_config table version column for thold to the prior version and the upgrade will rerun.

**Comment by gdsotirov** [comment] 2020-12-09 12:12
You mean there is upgrade of the database included with plugin upgrade? Why it didn't happened in my case then? Because I first uninstalled the plugin?

**Comment by TheWitness** [comment] 2020-12-09 13:12
No idea.  Was it stock or modified in some way.  Could of been the way that it was upgraded.  Here is what you can do:

1) Download the latest audit_database.php from the cli directory of the latest 1.2.x branch
2) Restore the tables as they were
3) Update the plugin config to the prior version
4) Run ./audit_database.php --upgrade

Let us know if that fixes things or if you get errors.  Better have your crontab disabled when you restore the tables to be able to separate chaf from load.

**Comment by gdsotirov** [comment] 2020-12-09 13:50
OK. It may not have become clear, but I already managed to restore thold plugin data from backup in my own way, so I have the thresholds back in Cacti. Hopefully backups saved the day :-)

However, what still bugs me is:

- is it normal for a plugin to remove user data on uninstall? You mentioned that there is a "warning" on uninstall, but I do not recall such thing. I just clicked the gear for "Uninstall plugin" and it worked... I would rather prefer the option to keep data if available.
- what is the correct procedure for upgrading plugins?

**Comment by bmfmancini** [comment] 2020-12-09 14:10
I'm not sure why no warning but the procedure I've used is usually this

Disable plugin
Move old plugin dir to tmp
Download and extract new plugin
Set proper permissions
Re-enable the plugin

**Comment by gdsotirov** [comment] 2020-12-09 15:46
OK. I follow this procedure from now on. Is it documented somewhere?

**Comment by gdsotirov** [comment] 2020-12-13 07:33
I just upgraded [plugin_monitor](https://github.com/Cacti/plugin_monitor) in the way suggested by @bmfmancini above and it worked fine. However, I'll keep this issue open, because it still bugs me that:

- I saw no warning on uninstalling plugin that all it's data (including settings and user data) would be deleted;
- I believe a plugin should **not** delete it's data (including settings and user data like templated thresholds) or at least this should be an option.
- Upgrading plugins should be documented. I personally wasn't able to find the right procedure.

**Comment by bmfmancini** [comment] 2020-12-13 14:48
I will update the documentation with that procedure

But I'm not so sure that uninstalling a plugin should not remove the plugin
data  I think it should since you are uninstalling it I would expect all
related data from that plugin should be removed

Maybe a notification or prompt can be made were you have to type something
rather than click ok before the uninstall ?

**Comment by gdsotirov** [comment] 2020-12-16 16:54
Thanks for updating the docs. Let me know the URL when done.

My point is that uninstalling a plugin should be like uninstalling a package on a Linux system. If you only want to remove the application you use `apt remove`, but if you'd like to remove everything (e.g. configuration files, data, etc.) you use `apt purge`.

I really do not want to end up in the situation I described in this issue again, because it cost me time and efforts to restore the deleted data, but in few months or years I may not remember this discussion. I'd like to be able to choose whether to remove all data of the plugin or leave it, because this would make me properly consider the situation and select the right option. Having plugin data directly deleted on uninstall without any warning or option is not prone to errors.

**Comment by cigamit** [comment] 2020-12-16 17:06
The only reason to ever uninstall a plugin is to remove it completely.  Removing a plugin should leave no trace of the plugin ever existing.  While I would be fine with a popup warning alerting that it is going to remove all database data related to the plugin, I don't want to change the behavior of how uninstalling itself works.

**Comment by gdsotirov** [comment] 2020-12-16 17:07
Sure, a popup explaining what would happen on uninstall would be useful.

**Comment by TheWitness** [comment] 2021-03-25 23:23
It's supposed to, but it looks like there was a regression in the latest 1.2.16 release.  Fixed now.

**Closed as completed by TheWitness** 2021-03-25 23:23 UTC

**Comment by gdsotirov** [comment] 2021-03-26 06:49
Thanks for the fix!
