### ISSUE TITLE
Is Issue with Net-SNMP - CPU Utilization ssCpuUser current value ?

### ISSUE THREAD

**Issue by akai1983** [Cacti/plugin_thold#328] opened 2019-05-28 09:21 UTC
**Describe the bug**
Net-SNMP - CPU Utilization ssCpuUser current value allows 0 ?

**Screenshots**
![image](https://user-images.githubusercontent.com/51112119/58466364-1dec7e80-816c-11e9-8909-11f8312723a8.png)

![image](https://user-images.githubusercontent.com/51112119/58466612-90f5f500-816c-11e9-8930-916d13616aa9.png)

**Plugin (please complete the following information):**
 - Version: cacti 1.2.3 + thold 1.2.4
 - Source:  github
 

**Desktop (please complete the following information):**
 - OS: windows 7
 - Browser chrome latest

**Comment by TheWitness** [comment] 2019-06-08 16:55
Can you please update to the latest version, then re-create the threshold.  I think this issue will be resolved then.  Issue was fixed several days ago.

**Comment by TheWitness** [comment] 2019-06-08 16:56
Duplicate of issue #323

**Closed as completed by TheWitness** 2019-06-08 16:56 UTC
Labels: duplicate

**Comment by akai1983** [comment] 2019-06-10 08:49
It was fixed. test at 2019-06-10. thanks.
