### ISSUE TITLE
Duplicated data source Item (tab) when creating new/editing standalone threshold

### ISSUE THREAD

**Issue by diazdw** [Cacti/plugin_thold#333] opened 2019-05-30 03:02 UTC
**Describe the bug**
Duplicated data source Item (tab) when creating new/editing standalone threshold for a Generic 4 OID templated based graph

**To Reproduce**
1. Go to graph
2. Click on 'Create threshold'
3. Scroll down to 'Data source Items' tabs
4. See the third data source item tab is duplicated

**Expected behavior**
Correct data source item tab quantity.

**Screenshots**
![image](https://user-images.githubusercontent.com/50931653/58605329-99c1f600-8254-11e9-8556-fe3cef8aeb59.png)

**Plugin (please complete the following information):**
 - Version: 1.2.4
 - Source: github (development)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chromium
 - Version 73.0

**Comment by TheWitness** [comment] 2019-06-08 16:32
Duplicate of Issue #319

**Closed as completed** 2019-06-08 16:32 UTC
Labels: duplicate
