### ISSUE TITLE
WarnEmails is not saved

### ISSUE THREAD

**Issue by flare2707** [Cacti/plugin_thold#544] opened 2022-01-05 07:18 UTC
**Describe the bug**
WarnEmails is not saved if applied via Warning Notification List or Notify Accounts. WarnEmails is only saved is address(s) is entered in Warning Emails dialog box.

**To Reproduce**
1. Go to 'Management' --> Thresholds --> Select Device 
2. Edit Warning Notification List and / or Notify accounts
3. Save
4. Logs shows entry for WarnEmails is blank..

`05-Jan-2022 18:06:44 - THOLD: Threshold Modified by User[1] TH[2] DataTemplate[Unix - Ping Host] DataSource[ping] Type[High / Low] Enabled[on] High[250] Low[] Trigger[5 Minutes] WarnHigh[] WarnLow[] WarnTrigger[5 Minutes] CDEF[0] ReAlert[12 Hours] AlertEmails[xxx.yyy@gmail.com] **WarnEmails[]**`

![image](https://user-images.githubusercontent.com/97142038/148176261-3178335a-ea2a-478a-a1e1-a83db66d7bea.png)

**Expected behavior**
WarnEmails[] should save email addresses selected via Warning Notification List and Alert Notification List

**Plugin (please complete the following information):**
 - THOLD Version: 1.5.2
 - Cacti Version : 1.2.19

**Comment by TheWitness** [comment] 2022-02-13 18:33
There is a fix in Cacti 1.2.20 that when release will properly de-duplicate emails.  Certain mail systems are not permitting the Email currently if the recipients are duplicated between a notification list and the legacy Emails.  I frankly would move away from the legacy notification emails and stick with the Notification Lists.

**Comment by TheWitness** [comment] 2022-02-13 18:33
Marking this duplicate, since I believe the problem is fixed in 1.2.20.

**Comment by TheWitness** [comment] 2023-07-20 23:28
This appears to have been a Cacti issue

**Closed as not planned** 2023-07-20 23:28 UTC
Labels: duplicate, 3rd party bug
