### ISSUE TITLE
Cacti Thold - Cannot create Thold from Graph

### ISSUE THREAD

**Issue by mikepiko** [Cacti/plugin_thold#439] opened 2020-08-06 12:40 UTC
Hi,

i cannot create a new Thold from a Graph. 

it creates SQL Errors:

`2020/08/06 14:23:33 - CMDPHP SQL Backtrace: (/plugins/thold/thold.php[83]:thold_add(), /plugins/thold/thold.php[191]:thold_add_graphs_action_prepare(), /plugins/thold/thold_webapi.php[171]:thold_wizard(), /plugins/thold/thold_webapi.php[654]:get_allowed_devices(), /lib/auth.php[2002]:db_fetch_cell(), /lib/database.php[386]:db_fetch_cell_prepared(), /lib/database.php[402]:db_execute_prepared())
2020/08/06 14:23:33 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND host_template_id IN (5) AND (IFNULL(h.disabled,"")="") HAVING (user0 IS N...' at line 1
2020/08/06 14:23:33 - CMDPHP SQL Backtrace: (/plugins/thold/thold.php[83]:thold_add(), /plugins/thold/thold.php[191]:thold_add_graphs_action_prepare(), /plugins/thold/thold_webapi.php[171]:thold_wizard(), /plugins/thold/thold_webapi.php[654]:get_allowed_devices(), /lib/auth.php[1986]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
2020/08/06 14:23:33 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND host_template_id IN (5) AND (IFNULL(h.disabled,"")="") HAVING (user0 IS N...' at line 1`

Steps to Reproduce:
I click on "create thold" next to the Graph:

![image](https://user-images.githubusercontent.com/38277702/89532384-fd00ce00-d7f1-11ea-9bdd-37eb0739219f.png)

Then the Wizard starts:

![image](https://user-images.githubusercontent.com/38277702/89532513-30dbf380-d7f2-11ea-84bf-020d1c25aedd.png)

And when i select a Datasource, the Window collapses:

![image](https://user-images.githubusercontent.com/38277702/89532593-51a44900-d7f2-11ea-91dc-65f2132ebd28.png)

When i select the Device, i get the List of possible Graphs, but after that the Window collapses again.

**Plugin (please complete the following information):**
 - Version: 1.4-devel
 - Source: [github]

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Chrome or Firefox - Same Problem]

**Additional context**
Cacti Version : 1.2.14
MariaDB 10.3.23-1
Debian bullseye/sid

**Comment by TheWitness** [comment] 2020-09-12 16:11
Thinking that this is a duplicate of #429.  Can you sync your thold, and then try again.

**Comment by TheWitness** [comment] 2020-09-13 14:04
I've confirmed that this is working now.  So, please test using the latest code anyway, but note that when the official 1.5 is released, you may have to rollback your version before implementing the real release.  That's achieved by running the following SQL statement, then updating the plugin, followed by going to the Thold tab to force the re-upgrade.

```sql
UPDATE plugin_config SET version = '1.4' WHERE directory = 'thold';
```

**Closed as completed** 2020-09-13 14:05 UTC
Labels: duplicate
