### ISSUE TITLE
THOLD Device UP DOWN

### ISSUE THREAD

**Issue by chathurag** [Cacti/plugin_thold#192] opened 2018-05-15 16:49 UTC
Dead peer notifications sent more than once if the device is down for a long time. NO way to acknowledge and stop notifications

**Comment by cigamit** [comment] 2018-08-13 13:35
Host Up / Down notifications are actually handled by Monitor now.  Never the less, this is a duplicate of #134

**Closed as completed by cigamit** 2018-08-13 13:35 UTC
