### ISSUE TITLE
Custom Subject Line for Alert/Warning Message

### ISSUE THREAD

**Issue by chris-technicate** [Cacti/plugin_thold#156] opened 2018-02-21 13:52 UTC
The "Down Device Subject" and "Recovering Device Subject" are customizable. Would it be possible to add the functionality to allow customization of the subject line for the Threshold Alert and Threshold Warning Messages?

**Comment by netniV** [comment] 2018-09-20 19:17
I believe this to be an extension or duplicate of #135 so I would post in that thread to get notified of updates to it.

**Closed as completed by netniV** 2018-09-20 19:17 UTC
Labels: enhancement, notification
