### ISSUE TITLE
Can not replace thold name to correct one and description display incorrect with long name 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_thold#357] opened 2019-08-01 04:01 UTC
1) Create a threshold like below, the thold description does not replace well with correct value and the waring/Alert description can not display well due to name is too long **--failed** 
![Screen Shot 2019-08-01 at 11 16 42 AM](https://user-images.githubusercontent.com/47589910/62263329-66673780-b44e-11e9-8bb9-634cbfb92465.png)
![Screen Shot 2019-08-01 at 11 29 43 AM](https://user-images.githubusercontent.com/47589910/62263710-c9a59980-b44f-11e9-90c6-b7fb331c8d0d.png)

found workaround step below: 
2) Go to Template - Data Source, Click the Data Source and directly click save 
![Screen Shot 2019-08-01 at 11 14 26 AM](https://user-images.githubusercontent.com/47589910/62263420-bcd47600-b44e-11e9-901b-a52bcbc57ae9.png)

3) Go to Threshold page, check the created threshold, the description can be updated well. 
![Screen Shot 2019-08-01 at 11 24 03 AM](https://user-images.githubusercontent.com/47589910/62264779-f52a8300-b453-11e9-8ccd-89299a1e6525.png)

Expect behavior:  after creating the threshold, the description can be replace well. 

problem2: 
The Alert/Warning description can not display well. 
Workaround: change the thold name, then can display well 
![Screen Shot 2019-08-01 at 11 26 34 AM](https://user-images.githubusercontent.com/47589910/62263616-83503a80-b44f-11e9-9e28-c102e89ef2b5.png)

Expect behavior: the Alert/Waring description can display well for such threshold 

Cacti 1.2.4
Thold 1.3.1 
FF
rhel7 x86

**Comment by TheWitness** [comment] 2020-03-01 21:57
Please feel free to suggest a pull request for this one @yingbaiibm.  Hope all is well...

**Comment by TheWitness** [comment] 2020-09-13 15:36
@yingbaiibm, are there plans to create a pull request?  If not, I will go ahead and close this.

**Comment by yingbaiibm** [comment] 2020-09-14 03:20
> @yingbaiibm, are there plans to create a pull request? If not, I will go ahead and close this.

Not currently, We do not fix this yet,  we will check if time allow for the fix in our next coming release.

**Comment by TheWitness** [comment] 2020-10-28 16:30
For the naming issue, I'm unable to reproduce with Cacti 1.2.15, but still checking on the break issue.

**Comment by TheWitness** [comment] 2020-10-28 16:37
When using a more recent version of RRDtool, there is no wrapping.  This is a third party bug with RRDtool.  So, I'm going to mark this 3rd party and close.  With RRDtool 1.7, it seems to work as expected.

**Closed as completed** 2020-10-28 16:38 UTC
Labels: 3rd party bug
