### ISSUE TITLE
threshold last traffic_in is different from graph

### ISSUE THREAD

**Issue by liangjiady** [Cacti/plugin_thold#432] opened 2020-05-20 09:33 UTC
i create thold but there is one error:
error information file:
<img width="576" alt="error" src="https://user-images.githubusercontent.com/41409395/82430406-db7c2a00-9abf-11ea-881b-154f7011f2aa.png">
what is going on ?who can tell me?
thanks!

**Comment by TheWitness** [comment] 2020-06-19 12:25
Not too sure.  There is not enough information included in this ticket.

**Comment by TheWitness** [comment] 2020-09-12 16:21
looking at this where I can see it now, this looks quite odd.  Show the entire thold edit form including data maniuplation.

**Comment by thowo** [comment] 2020-10-05 12:51
Hello,
the same issue as described arrises here. I will try to explain:
I created a threshold template based on CDEF (Percentage Bandwidth Used) which comes with cacti, the values which will be feeded to thold and the resulting calculation are an open book to me. The "current" from the graph is not the same as the "value" in thold.

I try to calculate the used bandwidth on wan links, calculate the percentage over ifSpeed (CDEF Percentage Bandwidth used) and threshold the resulting value over 2 poll cycles (10 mins), so I a WAN Link is satured over 80percent over the amount of 10min I want to get an alert (fire a script). In former releases of cacti (i.e. 0.8.9x) this has worked out of the box. I read up some issue descriptions here, but did not get the point on whats going on here. Can you please shed some light on this?

Thanks in advance,

best regards,
Thomas

Percentage Bandwidth Utilization:

cdef=CURRENT_DATA_SOURCE,|query_ifSpeed|,/,100,*,8,*


The Thold details:

![cacti_thold_details](https://user-images.githubusercontent.com/1064854/95081616-1652c780-071a-11eb-9802-9f5f5074b4bc.PNG)


The thold template:

![cacti_thold_template](https://user-images.githubusercontent.com/1064854/95081717-3d10fe00-071a-11eb-801c-19c4f3962833.PNG)



Currently the values feeded to thold are the following:
2020/10/05 14:15:10 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '0'
2020/10/05 14:20:12 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '23.055381762193'
2020/10/05 14:25:11 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '24.747192251686'
2020/10/05 14:30:13 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '25.982622056957'
2020/10/05 14:35:14 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '27.269473113635'
2020/10/05 14:40:11 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '27.801280763745'
2020/10/05 14:45:11 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '30.045956329671'
2020/10/05 14:50:12 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '31.180061822499'
2020/10/05 14:55:10 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '32.766690884228'
2020/10/05 15:00:12 - THOLD: Checking Threshold: Name: 'traffic_in', local_data_id: '9801', data_template_rrd_id: '19703', value: '35.033011160769'

whereas the graph for the same time range shows this:

![graph_1415-1505](https://user-images.githubusercontent.com/1064854/95083216-7d717b80-071c-11eb-8583-0096fca25771.PNG)

**Comment by TheWitness** [comment] 2020-10-28 16:03
The cdef issue has been resolved.  Please update to the latest version or wait for the 1.5 release to be issued.

**Comment by TheWitness** [comment] 2020-10-28 16:04
Duplicate of #450 and #446

**Closed as completed by TheWitness** 2020-10-28 16:04 UTC
Labels: duplicate, resolved
