### ISSUE TITLE
Aacknowledgement text does not visible  but shows up when you refresh 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_thold#496] opened 2021-03-20 01:25 UTC
When you acknowledge a thold you are able to provide a message 
the message does not show but if you refresh it shows momentarily 

Cacti 1.2.16
Thold 1.5.3
Browser Chrome,Firefox

![thold-log-bug](https://user-images.githubusercontent.com/13388748/111855140-779dda00-88f9-11eb-9f90-e4612d744c89.gif)

**Comment by bmfmancini** [comment] 2021-03-20 13:33
Forgot to mention no browser console errors

**Comment by ikorzha** [comment] 2021-03-26 03:20
This hasn't been fixed by latest commit. I believe the issue is that text is too long and doesn't fit into allowed field, hence the observed behavior..
![image](https://user-images.githubusercontent.com/11211789/112572498-a536c780-8dc0-11eb-98e3-f3b9bead34c6.png)
.

**Comment by TheWitness** [comment] 2021-03-26 03:22
Use incognito mode.

**Comment by ikorzha** [comment] 2021-03-26 03:31
You are absolutely right. I have tested in incognito more and comment is now properly visibile. This issue is resolved and can be close.
TheWitness if I may ask you to look into and resolve issue :THOLD ERROR: RPN Expression is invalid! BUG #495
It is absolutely critical as I am unable to do any link bandwidth % RPN since I have upgraded from Thold v 1.0.6 to latest....
It would be greatly appreciated as we greatly rely on that RPN feature...

**Closed as completed** 2021-08-13 13:36 UTC
Labels: bug, resolved
