### ISSUE TITLE
ERROR PHP NOTICE: Undefined offset

### ISSUE THREAD

**Issue by DigitalPackrat** [Cacti/plugin_thold#190] opened 2018-05-14 09:33 UTC
I am getting an error logged every time thold_graph.php is viewed by someone.

`2018/05/14 04:22:32 - CMDPHP PHP ERROR NOTICE Backtrace: (E:\Apache24\htdocs\cacti\plugins\thold\thold_graph.php: 57 tholds)(E:\Apache24\htdocs\cacti\plugins\thold\thold_graph.php: 447 CactiErrorHandler)(E:\Apache24\htdocs\cacti\lib\functions.php: 4590 cacti_debug_backtrace)  
2018/05/14 04:22:32 - ERROR PHP NOTICE: Undefined offset: 72 in file: E:\Apache24\htdocs\cacti\plugins\thold\thold_graph.php on line: 447  
`
If I comment out line 447 the one thing that doesn't show up is triggered value for baseline deviation. For high/low under triggered it says Yes if triggered. Under the baseline deviation tholds it shows Baseline-LOW. The error doesn't seem to cause any issues and I think it showed up after upgrading to Cacti 1.1.38. Thold was on 1.0.4 when the error showed up, upgrading to 1.0.5 dev didn't make any difference.

Line 447
`print "<td class='right nowrap'>" . $timearray[$row['bl_ref_time_range']/300]. '</td>';;`

**Comment by netniV** [comment] 2018-05-14 09:53
This is to do with selecting the element out of the timearray:
```
$timearray[$row['bl_ref_time_range']/300]
```

I'll have to check tonight for more detail on why that would be an issue as I'm currently dealing with a downed VMware host

**Comment by cigamit** [comment] 2018-05-14 23:42
Please update the three files from the last commit and let us know if the issue is resolved.

**Comment by DigitalPackrat** [comment] 2018-05-15 05:51
I updated the files but the error is the same.

**Comment by TheWitness** [comment] 2018-12-28 19:25
Please test using this commit.  Note, this is a large change.

https://github.com/Cacti/plugin_thold/commit/0ad5286c970b90dbaac68a74ba910665853e2e71

**Comment by TheWitness** [comment] 2018-12-29 00:12
This is resolved in the latest develop.  Keeping open for a time.

**Closed as completed** 2019-02-02 00:31 UTC
Labels: resolved
