### ISSUE TITLE
Wrong "Current Value" after migrating from Cacti 0.8.8b to 1.2.11

### ISSUE THREAD

**Issue by HorridFlyer** [Cacti/plugin_thold#416] opened 2020-04-10 11:24 UTC
I currently have hundreds of thresholds on production server running Cacti 0.8.8b, and I need to migrate everything on a new VM running CentOS 7 and Cacti 1.2.11 (installed 1.2.10 from yum, then upgraded to 1.2.11 cloning the git repo). Thold installed via Git too. Poller is spine 1.2.10 from yum, as I didn't find the 1.2.11 version.

I imported the db, and all the thresholds are where they're supposed to be, anyway I noticed that:
_thresholds for bits/s graphs are OK
_thresholds for bytes/s graph show huge "current values" even though real values are far lower

In the screenshot you can see 4 thresholds for the same graph, the two original in/out in the first/third tabs (using CDEF/turn-bytes-into-bits) imported from 0.8.8b, plus two I just added from scratch using EXACT-Value in the second/fourth tabs:

![image](https://user-images.githubusercontent.com/63452412/78986606-e8eedd80-7b2b-11ea-96bd-458b01688e78.png)

When using EXACT Value you can notice the last/current values are now matching the graph values, but the Hi/Low thresholds are now being multiplied by 8! So in any case I have a wrong behavior, getting false alerts or no alerts at all.
To make it work I had to specify bytes values on Hi/Low thresholds (I divided by 8 the original threshold values):

![image](https://user-images.githubusercontent.com/63452412/78987173-8991cd00-7b2d-11ea-9290-c03349adf1fc.png)

 Is there a way to quickly fix this or should I manually modify all of them?

Grazie!

**Comment by HorridFlyer** [comment] 2020-04-17 12:12
Ok I did it directly in the db.
Of course It would have been easier if I had my thresholds generated via template, in that case I would have modified that template and then performed the "Propagate Template" action on each threshold, but this was not the case. So this is what I did:

`UPDATE thold_data SET thold_hi=thold_hi/8, thold_low=thold_low/8, data_type=0 where data_type=1 and cdef=2;`

I set data_type=0(Exact-Value) and divided by 8 actual hi/low values for all of those thresholds with data_type=1(CDEF) and cdef=2(Turn Bytes into Bits).

**Comment by HorridFlyer** [comment] 2020-04-18 17:39
I'm sorry but I have to reopen this. 
Don't know where exactly I saw everything was fine after setting Exact-Values and hi/low values as bytes, because it's not fine at all! Current values are far from being correct, so forget about everything I wrote above, I apologize.

In Cacti 0.8.8b, to have a working threshold for those graphs I set hi/low values in bits/s, and set CDEF Turn bytes into bits. And it works good.
In this latest version, the same settings are causing the “Current” value to be far lower than reality. If my link bitrate is at 2.39G, thold reads 95.58M, that is approximatively 25 times lower. Odd.
If I look in the db, "lastread" value is 11947492.515467, so it looks like thold performs “lastread”*8 to get “Current” value. For the same threshold, on the older Cacti the “lastread” value is exactly 2.39G /8, thus no problem is seen on that version. So, where does “lastread” comes from? The difference is in there, but it’s hard for me to find out in which part of the many thold scripts it is calculated. 

In issue #361 a user had the same problem, but that was closed as "not a bug" because the problem is the graph was in bits/s whereas the threshold template was in bytes/s. I can’t really understand this, I'm having problems with those devices that are sending bytes values back to the poller (e.g. Cisco) whilst I have no problems with those devices that are sending back bits values (e.g Juniper). The affected devices are polled via default "SNMP - Interface Statistics" data query, and the resulting graphs are correctly drawed in bits/s. I guess it is in the graph template where bytes are then displayed as bits, but still I don’t get why thold is behaving that way.

In the meantime I added this at line 3677 of thold_functions.php:
`$thold_data['lastread']  *= 25;`

With that function, my thresholds are no longer generating false alarms (I had to set them up with Exact-Value and hi/low values in bytes/s) because current in/out values are now pretty close to the real ones:

![image](https://user-images.githubusercontent.com/63452412/79644860-ec2d3d80-81ab-11ea-8baf-d085e40c6a90.png)

The other thresholds (Juniper) have not been affected by this mod, so actually it seems to be a valid workaround. Of course I would prefer a real solution..

**Comment by TheWitness** [comment] 2020-09-12 16:22
Can you please show the entirety of the thold edit form.  Are you including a CDEF in the Data Manipulation section?

**Comment by HorridFlyer** [comment] 2020-09-16 12:56
Here it is.

_ no cdef (Exact Value)
_ hi/low values in Bytes

Please note the wrong value in the red circle, and the calculated one in the blue circle (after the *25 multiplier), you can see it is now pretty close to the correct value in the green circle

![affected_thold_part_1](https://user-images.githubusercontent.com/63452412/93339039-6cbf9b00-f82b-11ea-85ef-ab38c68a7180.png)
![affected_thold_part_2](https://user-images.githubusercontent.com/63452412/93339066-70ebb880-f82b-11ea-920e-22d1782ae63e.png)

**Comment by TheWitness** [comment] 2020-10-28 16:02
Please update to the latest develop version.  Thanks!

**Comment by TheWitness** [comment] 2020-10-28 16:05
Duplicate of #446 and #450.  However, will check on a bits/second template to validate prior to closing.

**Comment by TheWitness** [comment] 2020-10-28 16:09
Please review the following.  This is working as expected now in the develop branch.  Will be releasing on Friday.

![BitsPerSecondBytesPerSecond](https://user-images.githubusercontent.com/1439914/97463720-6df9e280-1916-11eb-8789-c3439b556c4d.gif)

**Closed as completed** 2020-10-28 16:10 UTC
Labels: duplicate, resolved
