### ISSUE TITLE
Undefined variable $local_data_id in thold_check_function()

### ISSUE THREAD

**Issue by Damianb0** [Cacti/plugin_thold#174] opened 2018-03-13 11:56 UTC
In Time Based threshold type thold send Normal notification although the trigger count was not reached and thold was not send any Warning/Alert notification.

Actually why have situation when trigger is for example 2-3 and Trigger Count is set to 5, then when in next poller data field return below high-low Thold send Normal notification but the Time Based rules was not reached.

**Comment by netniV** [comment] 2018-03-13 12:20
Apologies, but your broken english is a little tricky to understand.  Are you saying, when using a time based notification, you manage to receive a "NORMAL: " notification despite the fact that you never TRIGGERED/BREACHED the threshold?

**Comment by Damianb0** [comment] 2018-03-13 12:45
If you mean "never TRIGGERED/BREACHED the threshold" like never reached Trigged Count - yes, that's the point.

![thold](https://user-images.githubusercontent.com/37333753/37345462-4ff07b02-26cd-11e8-8f7b-747c2b4b8ec7.PNG)

**Comment by netniV** [comment] 2018-03-19 08:38
OK, thanks for that.  I'll try and see if I can spot anything but it may be a day or two.

**Comment by tddcacti** [comment] 2018-03-26 21:05
Adding this comment per @netniV's request in Issue 825 (https://github.com/Cacti/cacti/issues/825).

 I am experiencing a similar problem, here are my findings.

In my case this issue started when I went to use a time based threshold for the first time. 

In the logs I started to see lots of errors such as the following:

2017/06/23 16:08:54 - CMDPHP PHP ERROR NOTICE Backtrace: (/poller.php: 716 api_plugin_hook)(/lib/plugins.php: 69 api_plugin_run_plugin_hook)(/lib/plugins.php: 162 thold_poller_bottom)(/plugins/thold/includes/polling.php: 35 thold_check_all_thresholds)(/plugins/thold/includes/polling.php: 251 thold_check_threshold)(/plugins/thold/thold_functions.php: 2049 CactiErrorHandler)(/lib/functions.php: 4364 cacti_debug_backtrace)
2017/06/23 16:08:54 - ERROR PHP NOTICE in Plugin 'thold': Undefined variable: local_data_id in file: /home/cacti/plugins/thold/thold_functions.php on line: 2049

Looking at line 2049 in thold_functions.php and working my way backwards in the code, I see that $local_data_id is indeed never defined within the function thold_check_threshold.

To fix this I simply added the following on line 1569, just below a similar definition for $local_graph_id:

$local_data_id = $thold_data['local_data_id'];

This seems to be working for me. I checked the latest code for thold_functions.php, and unless I missed it, I'm still not seeing this fix in the latest file.

To give a bit more background for anyone who might be seeing this problem: I noticed two unexpected behaviors after enabling a time based threshold (set to 5 triggers in one hour). The first unexpected behavior was that I would receive a Resolved / Normal alert after just one trigger event--I didn't expect this to happen, since there had not been 5 trigger events and also I never received the alert email.

The second behavior was on a graph where the threshold was breached and stayed breached--I expected to receive the alert email after 5 polling cycles, but it never came.

In troubleshooting both of these things I found that the fact that $local_data_id is undefined causes $step to become blank in line 2049, which cascades and causes the logic further down to fail to increment $failures correctly--it would only ever get to 1, and then back to zero when the threshold breach cleared.

**Comment by netniV** [comment] 2018-03-26 22:00
I'll take a stab at a fix tomorrow based off your comments.  If you take a look at the following, you can decide if you want to do a pull request.  If you can do a difference instead, I can create the request.

https://github.com/netniV/cacti/wiki/Creating-Pull-Requests

**Comment by tddcacti** [comment] 2018-03-27 12:42
Thanks netniV.  Here is a diff of the original file against the one where I've made an edit:

1568a1569,1570
>       # Fix for issue #174, time based thresholds not working due to missing variable $local_data_id
>       $local_data_id = $thold_data['local_data_id'];

This is for version 1.0.2 of thold, which is what I have installed currently.

**Comment by netniV** [comment] 2018-03-27 13:19
Can you provide the lines around it to give some context, just in case  👍  I'll get this sorted tonight.

**Comment by tddcacti** [comment] 2018-03-27 13:37
No problem.  Here's the code starting from the beginning of the thold_check_threshold function:

```
function thold_check_threshold(&$thold_data) {
	global $config, $plugins, $debug, $thold_types;

	$name  = db_fetch_cell_prepared('SELECT data_source_name FROM data_template_rrd WHERE id = ?', array($thold_data['data_template_rrd_id']));

	thold_debug('Checking Threshold:' .
		' Name: ' . $name . 
		', local_data_id: ' . $thold_data['local_data_id'] . 
		', data_template_rrd_id: ' . $thold_data['data_template_rrd_id'] . 
		', value: ' . $thold_data['lastread']);

	$debug = false;

	if (!defined('STAT_HI')) {
		define('STAT_HI', 2);
	}

	if (!defined('STAT_LO')) {
		define('STAT_LO', 1);
	}

	if (!defined('STAT_NORMAL')) {
		define('STAT_NORMAL', 0);
	}

	// Do not proceed if we have chosen to globally disable all alerts
	if (read_config_option('thold_disable_all') == 'on') {
		thold_debug('Threshold checking is disabled globally');
		return;
	}

	$alert_exempt = read_config_option('alert_exempt');
	/* check for exemptions */
	$weekday = date('l');
	if (($weekday == 'Saturday' || $weekday == 'Sunday') && $alert_exempt == 'on') {
		thold_debug('Threshold checking is disabled by global weekend exemption');
		return;
	}

	/* check for the weekend exemption on the threshold level */
	if (($weekday == 'Saturday' || $weekday == 'Sunday') && $thold_data['exempt'] == 'on') {
		thold_debug('Threshold checking is disabled by global weekend exemption');
		return;
	}

	/* don't alert for this host if it's selected for maintenance */
	if (api_plugin_is_enabled('maint') || in_array('maint', $plugins)) {
		include_once($config['base_path'] . '/plugins/maint/functions.php');

		if (plugin_maint_check_cacti_host ($thold_data['host_id'])) {
			thold_debug('Threshold checking is disabled by maintenance schedule');
			return;
		}
	}

	$local_graph_id = $thold_data['local_graph_id'];
	# Fix for issue #174, time based thresholds not working due to missing variable $local_data_id 
	$local_data_id = $thold_data['local_data_id'];

	/* only alert if Device is in UP mode (not down, unknown, or recovering) */
	$h = db_fetch_row('SELECT * FROM host WHERE id=' . $thold_data['host_id']);
	if (sizeof($h) && $h['status'] != 3) {
		thold_debug('Threshold checking halted by Device Status (' . $h['status'] . ')' );
		return;
	}
```

**Comment by netniV** [comment] 2018-03-31 07:53
I've applied this fix now on the development branch.  If you can test and confirm that would be good.

**Comment by tddcacti** [comment] 2018-04-05 12:52
Sorry I haven't had a chance to get back to this.  Checking my own installation of Cacti, with the fix I applied, I'm unfortunately still seeing Normal notifications without any previous Warning/Alert conditions.  In my case I'm seeing the graph go above the threshold for one polling cycle, then back down below--and then I get a Normal notification.  My time-based alert is set for a minimum of 5 triggers in one hour.

I do think the fix you committed was needed, and it did solve several problems, however I think there may be some additional work needed.

I've started looking at the logic for time based tholds in thold_check_function(), and I have some theories on what might be wrong.

I've got a test server with Cacti installed; I'm going to upgrade it to the latest versions of Cacti and thold and see if they work any better; if not I will try to figure out what might need to be changed.

**Comment by tddcacti** [comment] 2018-04-10 01:37
Ok, I have my test server upgraded and am looking into this.

Looks like the issue with $local_data_id was already fixed in the latest version of thold.  The original line:

`$step = db_fetch_cell('SELECT rrd_step FROM data_template_data WHERE local_data_id = ' . $local_data_id, FALSE);`

Was replaced by this:

               $step = db_fetch_cell_prepared('SELECT rrd_step
                        FROM data_template_data
                        WHERE local_data_id = ?',
                        array($thold_data['local_data_id']));

However the behavior of the time based alert still isn't working properly; I'm investigating that.

**Comment by netniV** [comment] 2018-04-10 08:32
I've reopened this for now.  If you can provide your analysis that would be great.

**Comment by tddcacti** [comment] 2018-04-12 14:30
Thanks for reopening.  I've spent some time wrapping my head around the current code for time-based tholds.  It's entirely possible I have some basic misunderstandings of how it is supposed to work, so forgive me if that is the case.  However, assuming that's not the case, I think I've found a number of problems with the current code.

Below I will paste in the section of code that deals with time-based tholds, from the function thold_check_threshold in the fiel thold_functions.php.  The first line I am pasting is line 2349 in that file.

I've added my comments throughout the code, wherever you see comments that start with "Issue 174:".

One of the main problems I think I'm seeing is this: it appears that this section of code was adapted from the high/low thold option (case 0, which starts on line 1891).  The high/low threshold option is very focused on the current value of the data source being monitored, which makes sense for that option.

The time-based option (case 2) seems to have been written similarly, centered on the current value of the data source, which I'm thinking may not be the best approach, since time-based tholds are more concerned with all of the previous values of the data source (within the time period defined, and including the current value), and specifically what quantity of those values are beyond either the warning or alert thresholds. 

In the time-based model it is entirely possible for the current value of a data source to be distinct from the current state of the threshold.  For example, the current value could be normal, but the state of the threshold might still be warning/alert if there are enough previous warning/alert values in the time period.  Or, the current value could be alert, but since alerts are also counted as warnings, we could need to trigger a warning notification or warning re-notification.

Another main issue I see is that the code doesn't really try to check for the previous state of the threshold--this is why we're getting normal notifications when there hasn't previously been any warning or alert states.  It could also cause failure to send notification in some cases: for example if we are in a warning state, and have reached the re-notification interval, but the current value is either normal or alert, then that notification won't go out. 

Let me know what you think, and whether I'm missing something in any of my comments.  

I haven't yet really tried any edits to fix these issues; I'm not sure whether to keep the existing  structure and add to it (which I think could end up bloating the code unnecessarily), or if it would be better to rearrange the code so it is less centered around the current value of the data source (which might be more efficient).

Here is the section of code:

`

	case 2:	/* time based */
		if ($thold_data['lastread'] != '') {
			$breach_up           = ($thold_data['time_hi']          != '' && $thold_data['lastread'] > $thold_data['time_hi']);
			$breach_down         = ($thold_data['time_low']         != '' && $thold_data['lastread'] < $thold_data['time_low']);
			$warning_breach_up   = ($thold_data['time_warning_hi']  != '' && $thold_data['lastread'] > $thold_data['time_warning_hi']);
			$warning_breach_down = ($thold_data['time_warning_low'] != '' && $thold_data['lastread'] < $thold_data['time_warning_low']);
		} else {
			$breach_up = $breach_down = $warning_breach_up = $warning_breach_down = false;
		}

		$step = db_fetch_cell_prepared('SELECT rrd_step
			FROM data_template_data
			WHERE local_data_id = ?',
			array($thold_data['local_data_id']));

		/* alerts */
		$trigger  = $thold_data['time_fail_trigger'];
		
		# Issue 174: Should there be a bit of buffer added in order to account for slight variations in polling times?
		# Issue 174: In my testing the polling cycle is 60 seconds but the actual time of each cycle can vary by a second or two
		# Issue 174: Sometimes this means that the earliest cycle that should be included misses the cutoff by a second or two
		# Issue 174: Maybe we could add ~10 seconds as a buffer to avoid omitting a that earliest cycle?
		# Issue 174: Or maybe multiple $step by 1.5?
		$time     = time() - ($thold_data['time_fail_length'] * $step);

		# Issue 174: Would it be better to use the values stored in the "current" field instead of the "status" field?
		# Issue 174: If we assume "status" doesn't always correlate to warning or failure, for example the ST_NOTIFYRA status 
		# Issue 174: can occur during a cycle were the value is warning or even normal, so it is not a good indicator of failure
		# Issue 174: Instead we could use something like the count of entries where "current > time_hi"
		$failures = db_fetch_cell_prepared('SELECT count(id)
			FROM plugin_thold_log
			WHERE threshold_id = ?
			AND status IN (?, ?, ?)
			AND time > ?',
			array(
				$thold_data['id'],
				ST_TRIGGERA,
				ST_NOTIFYRA,
				ST_NOTIFYAL,
				$time
			)
		);

		/* warnings */
		$warning_trigger  = $thold_data['time_warning_fail_trigger'];

		# Issue 174: Same question as above: should there be a buffer added in order to account for slight variations in polling times?
		$warning_time     = time() - ($thold_data['time_warning_fail_length'] * $step);
		
		# Issue 174: Same question as above
		# Issue 174: Would it be better to use the values stored in the "current" field instead of the "status" field?
		$warning_failures = db_fetch_cell_prepared('SELECT count(id)
			FROM plugin_thold_log
			WHERE threshold_id = ?
			AND status IN (?, ?)
			AND time > ?',
			array(
				$thold_data['id'],
				ST_NOTIFYWA,
				ST_TRIGGERW,
				$warning_time
			)
		) + $failures;

		# Issue 174: do we want to treat breach low and breach hi as one?  Or should they be separate?
		# Issue 174: may not be a common use case but theoretically you could have a graph that is swinging
		# Issue 174: widely between breach_up and breach_down--what is the expected behavior in that case?
		if ($breach_up || $breach_down) {
			$notify = false;

			thold_debug('Threshold Time Based check breached HI:' . $thold_data['time_hi'] . ' LOW:' . $thold_data['time_low'] . ' VALUE:' . $thold_data['lastread']);

			$thold_data['thold_alert']      = ($breach_up ? STAT_HI:STAT_LO);
			# Issue 174: Is this line doing anything?  If so should it come after the $failures++ line below?
			$thold_data['thold_fail_count'] = $failures;

			/* we should only re-alert X minutes after last email, not every 5 pollings, etc...
			   re-alert? */
			$realerttime   = ($thold_data['repeat_alert']-1) * $step;
			$lastemailtime = db_fetch_cell_prepared('SELECT time
				FROM plugin_thold_log
				WHERE threshold_id = ?
				AND status IN (?, ?)
				ORDER BY time DESC
				LIMIT 1',
				array($thold_data['id'], ST_NOTIFYRA, ST_NOTIFYAL));

			# Issue 174: Should this come after the $failures++ line below?
			# Issue 174: It is also possible for re-alert to be needed if $failures = $trigger
			$ra = ($failures > $trigger && $thold_data['repeat_alert'] && !empty($lastemailtime) && ($lastemailtime+$realerttime <= time()));

			# Issue 174: should this not be incremented before the two places it is being referenced above?
			$failures++;

			thold_debug("Alert Time:'$time', Alert Trigger:'$trigger', Alert Failures:'$failures', RealertTime:'$realerttime', LastTime:'$lastemailtime', RA:'$ra', Diff:'" . ($realerttime+$lastemailtime) . "'<'". time() . "'");

			# Issue 174: shouldn't assume that $failures will only be equal to $trigger when the threshold breach first occurs.  In can be true at later points too
			# Issue 174: this can cause extra notifications to be sent
			if ($failures == $trigger || $ra) {
				$notify = true;
			}

			$subject = ($notify ? 'ALERT: ':'TRIGGER: ') . $thold_data['name'] . ($thold_show_datasource ? ' [' . $thold_data['data_source_name'] . ']' : '') . ' ' . ($failures > $trigger ? 'is still' : 'went') . ' ' . ($breach_up ? 'above' : 'below') . ' threshold of ' . ($breach_up ? $thold_data['time_hi'] : $thold_data['time_low']) . ' with ' . $thold_data['lastread'];

			if ($notify) {
				thold_debug('Alerting is necessary');

				if ($logset == 1) {
					logger($subject, $url);
				}

				$alert_emails = get_thold_alert_emails($thold_data);

				if (trim($alert_emails) != '') {
					$alert_msg = get_thold_alert_text($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread'], $thold_data['local_graph_id']);
					thold_mail($alert_emails, '', $subject, $alert_msg, $file_array);
				}

				if ($thold_snmp_traps) {
					$thold_snmp_data = get_thold_snmp_data($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread']);

					$thold_snmp_data['eventClass'] = 3;
					$thold_snmp_data['eventSeverity']         = $thold_data['snmp_event_severity'];
					$thold_snmp_data['eventStatus']           = $thold_data['thold_alert']+1;
					$thold_snmp_data['eventRealertStatus']    = ($ra ? ($breach_up ? 3:2) :1);
					$thold_snmp_data['eventNotificationType'] = ($failures > $trigger ? ST_NOTIFYAL:ST_NOTIFYRA)+1;
					$thold_snmp_data['eventFailCount']        = $failures;
					$thold_snmp_data['eventFailCountTrigger'] = $trigger;
					$thold_snmp_data['eventDeviceIp'] = gethostbyname($h['hostname']);

					$thold_snmp_data['eventDescription'] = str_replace('<FAIL_COUNT>', $thold_snmp_data['eventFailCount'], $thold_snmp_data['eventDescription']);

					thold_snmptrap($thold_snmp_data, SNMPAGENT_EVENT_SEVERITY_MEDIUM, $overwrite);
				}

				thold_log(array(
					'type'            => 2,
					'time'            => time(),
					'host_id'         => $thold_data['host_id'],
					'local_graph_id'  => $thold_data['local_graph_id'],
					'threshold_id'    => $thold_data['id'],
					'threshold_value' => ($breach_up ? $thold_data['time_hi'] : $thold_data['time_low']),
					'current'         => $thold_data['lastread'],
					# Issue 174: See above, it is possible for $failures to be equal to $trigger when a re-alert is needed, so maybe it would be better
					# Issue 174: to base "status" on some other logic?
					'status'          => ($failures > $trigger ? ST_NOTIFYAL:ST_NOTIFYRA),
					'description'     => $subject,
					'emails'          => $alert_emails)
				);
			} else {
				$alert_emails = get_thold_alert_emails($thold_data);

				thold_log(array(
					'type'            => 2,
					'time'            => time(),
					'host_id'         => $thold_data['host_id'],
					'local_graph_id'  => $thold_data['local_graph_id'],
					'threshold_id'    => $thold_data['id'],
					'threshold_value' => ($breach_up ? $thold_data['time_hi'] : $thold_data['time_low']),
					'current'         => $thold_data['lastread'],
					'status'          => ST_TRIGGERA,
					'description'     => $subject,
					'emails'          => $alert_emails)
				);
			}

			db_execute_prepared('UPDATE thold_data
				SET thold_alert = ?,
				thold_fail_count = ?
				WHERE id = ?',
				array($thold_data['thold_alert'], $failures, $thold_data['id']));

			# Issue 174: This is the end of the breach section, but what if we happen to be at a point where the warning level has just 
			# Issue 174: been passed and we need to send a warning notification, or warning re-alert notification needs to go out?
			# Issue 174: A current failure also counts as a warning, so it is possible we need to perform some warning actions




		# do we want to treat warning low and warning hi as one?  Or should they be separate?		
		} elseif ($warning_breach_up || $warning_breach_down) {
			$notify = false;

			$thold_data['thold_alert']              = ($warning_breach_up ? STAT_HI:STAT_LO);
			# Issue 174: Is this line doing anything?  If so should it come after the $warning_failures++ line below?
			$thold_data['thold_warning_fail_count'] = $warning_failures;

			/* we should only re-alert X minutes after last email, not every 5 pollings, etc...
			   re-alert? */
			$realerttime   = ($thold_data['time_warning_fail_length']-1) * $step;
			$lastemailtime = db_fetch_cell_prepared('SELECT time
				FROM plugin_thold_log
				WHERE threshold_id = ?
				AND status IN (?, ?)
				ORDER BY time DESC
				LIMIT 1',
				array($thold_data['id'], ST_NOTIFYRA, ST_NOTIFYWA));

			# Issue 174: Should this come after the $failures++ line below?
			# Issue 174: It is also possible for re-alert to be needed if $warning_failures = $trigger
			$ra = ($warning_failures > $warning_trigger && $thold_data['time_warning_fail_length'] && !empty($lastemailtime) && ($lastemailtime+$realerttime <= time()));

			# Issue 174: should this not be incremented before the two places it is being referenced above?
			$warning_failures++;

			thold_debug("Warn Time:'$warning_time', Warn Trigger:'$warning_trigger', Warn Failures:'$warning_failures', RealertTime:'$realerttime', LastTime:'$lastemailtime', RA:'$ra', Diff:'" . ($realerttime+$lastemailtime) . "'<'". time() . "'");

			# Issue 174: shouldn't assume that $warning_failures will only be equal to $warning_trigger when the threshold breach first occurs.  In can be true at later points too
			# Issue 174: this can cause extra notifications to be sent
			if ($warning_failures == $warning_trigger || $ra) {
				$notify = true;;
			}

			$subject = ($notify ? 'WARNING: ':'TRIGGER: ') . $thold_data['name'] . ($thold_show_datasource ? ' [' . $thold_data['data_source_name'] . ']' : '') . ' ' . ($warning_failures > $warning_trigger ? 'is still' : 'went') . ' ' . ($warning_breach_up ? 'above' : 'below') . ' threshold of ' . ($warning_breach_up ? $thold_data['time_warning_hi'] : $thold_data['time_warning_low']) . ' with ' . $thold_data['lastread'];

			if ($notify) {
				if ($logset == 1) {
					logger($subject, $url);
				}

				$alert_emails   = get_thold_alert_emails($thold_data);
				$warning_emails = get_thold_warning_emails($thold_data);

				if (trim($alert_emails) != '') {
					$warn_msg = get_thold_warning_text($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread'], $thold_data['local_graph_id']);
					thold_mail($warning_emails, '', $subject, $warn_msg, $file_array);
				}

				if ($thold_snmp_traps && $thold_snmp_warning_traps) {
					$thold_snmp_data = get_thold_snmp_data($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread']);

					$thold_snmp_data['eventClass']            = 2;
					$thold_snmp_data['eventSeverity']         = $thold_data['snmp_event_warning_severity'];
					$thold_snmp_data['eventStatus']           = $thold_data['thold_alert']+1;
					$thold_snmp_data['eventRealertStatus']    = ($ra ? ($warning_breach_up ? 3:2) :1);
					$thold_snmp_data['eventNotificationType'] = ($warning_failures > $warning_trigger ? ST_NOTIFYRA:ST_NOTIFYWA)+1;
					$thold_snmp_data['eventFailCount']        = $warning_failures;
					$thold_snmp_data['eventFailCountTrigger'] = $warning_trigger;
					$thold_snmp_data['eventDeviceIp'] = gethostbyname($h['hostname']);

					$thold_snmp_data['eventDescription'] = str_replace('<FAIL_COUNT>', $thold_snmp_data['eventFailCount'], $thold_snmp_data['eventDescription']);

					thold_snmptrap($thold_snmp_data, SNMPAGENT_EVENT_SEVERITY_MEDIUM, $overwrite);
				}

				thold_log(array(
					'type'            => 2,
					'time'            => time(),
					'host_id'         => $thold_data['host_id'],
					'local_graph_id'  => $thold_data['local_graph_id'],
					'threshold_id'    => $thold_data['id'],
					'threshold_value' => ($breach_up ? $thold_data['time_hi'] : $thold_data['time_low']),
					'current'         => $thold_data['lastread'],
					# Issue 174: See above, it is possible for $warning_failures to be equal to $warning_trigger when a re-alert is needed, so maybe it would be better
					# Issue 174: to base "status" on some other logic?
					'status'          => ($warning_failures > $warning_trigger ? ST_NOTIFYRA:ST_NOTIFYWA),
					'description'     => $subject,
					'emails'          => $alert_emails)
				);
			# Issue 174: This line should include some verification that we were actually in a alert failure state previously 
			# Issue 174: Otherwise it will be mistakenly applied in many cases where we should just be recording a ST_TRIGGERW event
			} elseif ($alertstat != 0 && $warning_failures < $warning_trigger && $failures < $trigger) {
				$subject = 'ALERT -> WARNING: '. $thold_data['name'] . ($thold_show_datasource ? ' [' . $thold_data['data_source_name'] . ']' : '') . ' restored to warning threshold with value ' . $thold_data['lastread'];

				$alert_emails = get_thold_alert_emails($thold_data);

				thold_log(array(
					'type'            => 2,
					'time'            => time(),
					'host_id'         => $thold_data['host_id'],
					'local_graph_id'  => $thold_data['local_graph_id'],
					'threshold_id'    => $thold_data['id'],
					'threshold_value' => ($warning_breach_up ? $thold_data['time_hi'] : $thold_data['time_low']),
					'current'         => $thold_data['lastread'],
					'status'          => ST_NOTIFYAW,
					'description'     => $subject,
					'emails'          => $alert_emails)
				);
			} else {
				$warning_emails = get_thold_warning_emails($thold_data);

				thold_log(array(
					'type'            => 2,
					'time'            => time(),
					'host_id'         => $thold_data['host_id'],
					'local_graph_id'  => $thold_data['local_graph_id'],
					'threshold_id'    => $thold_data['id'],
					'threshold_value' => ($warning_breach_up ? $thold_data['time_hi'] : $thold_data['time_low']),
					'current'         => $thold_data['lastread'],
					'status'          => ST_TRIGGERW,
					'description'     => $subject,
					'emails'          => $warning_emails)
				);
			}
			
			# what if we happen to be at a point where re-alert notification needs to go out?  Or if we have just dropped down from alert back to warning?

			db_execute_prepared('UPDATE thold_data
				SET thold_alert = ?,
				thold_warning_fail_count = ?,
				thold_fail_count = ?
				WHERE id = ?',
				array($thold_data['thold_alert'], $warning_failures, $failures, $thold_data['id']));
				
			
			# Issue 174: This is the end of the breach section, but what if we happen to be at a point where a failure re-alert notification 
			# Issue 174: needs to go out?  Just because the current value is warning doesn't mean we aren't still in a failure alert state
				
				
		} else {
			thold_debug('Threshold Time Based check is normal HI:' . $thold_data['time_hi'] . ' LOW:' . $thold_data['time_low'] . ' VALUE:' . $thold_data['lastread']);

			# Issue 174: This line should include some verification that we were actually in a alert failure or alert warning state previously 
			# Issue 174: Otherwise it will send restoral notifications any time we have a normal value after even a single warning/failure value
			# Issue 174: (this is the original problem for which Issue 174 was opened)
			if ($alertstat != 0 && $warning_failures < $warning_trigger && $thold_data['restored_alert'] != 'on') {
				$subject = 'NORMAL: ' . $thold_data['name'] . ($thold_show_datasource ? ' [' . $thold_data['data_source_name'] . ']' : '') . ' restored to normal threshold with value ' . $thold_data['lastread'];

				if ($logset == 1) {
					logger($subject, $url);
				}

				$warning_emails = get_thold_warning_emails($thold_data);

				if (trim($warning_emails) != '' && $thold_data['restored_alert'] != 'on') {
					$alert_msg = get_thold_alert_text($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread'], $thold_data['local_graph_id']);
					thold_mail($warning_emails, '', $subject, $alert_msg, $file_array);
				}

				if ($thold_snmp_traps && $thold_snmp_normal_traps) {
					$thold_snmp_data = get_thold_snmp_data($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread']);

					$thold_snmp_data['eventClass'] = 1;
					$thold_snmp_data['eventSeverity'] = 1;
					$thold_snmp_data['eventStatus'] = 1;
					$thold_snmp_data['eventNotificationType'] = ST_NOTIFYRS+1;
					$thold_snmp_data['eventDeviceIp'] = gethostbyname($h['hostname']);

					thold_snmptrap($thold_snmp_data, SNMPAGENT_EVENT_SEVERITY_MEDIUM, $overwrite);
				}

				thold_log(array(
					'type'            => 2,
					'time'            => time(),
					'host_id'         => $thold_data['host_id'],
					'local_graph_id'  => $thold_data['local_graph_id'],
					'threshold_id'    => $thold_data['id'],
					'threshold_value' => '',
					'current'         => $thold_data['lastread'],
					'status'          => ST_NOTIFYRS,
					'description'     => $subject,
					'emails'          => $warning_emails)
				);

				db_execute_prepared('UPDATE thold_data
					SET thold_alert = 0,
					thold_warning_fail_count = ?,
					thold_fail_count = ?
					WHERE id = ?',
					array($warning_failures, $failures, $thold_data['id']));
			# Issue 174: This line should include some verification that we were actually in a alert failure state previously 
			# Issue 174: Otherwise it will send notification when we have a normal value while in a warning state
			} elseif ($alertstat != 0 && $failures < $trigger && $thold_data['restored_alert'] != 'on') {
				$subject = 'NORMAL: ' . $thold_data['name'] . ($thold_show_datasource ? ' [' . $thold_data['data_source_name'] . ']' : '') . ' restored to warning threshold with value ' . $thold_data['lastread'];

				if ($logset == 1) {
					logger($subject, $url);
				}

				$alert_emails = get_thold_alert_emails($thold_data);

				if (trim($alert_emails) != '' && $thold_data['restored_alert'] != 'on') {
					$alert_msg = get_thold_alert_text($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread'], $thold_data['local_graph_id']);
					thold_mail($alert_emails, '', $subject, $alert_msg, $file_array);
				}

				if ($thold_snmp_traps && $thold_snmp_normal_traps) {
					$thold_snmp_data = get_thold_snmp_data($thold_data['data_source_name'], $thold_data, $h, $thold_data['lastread']);

					$thold_snmp_data['eventClass']            = 1;
					$thold_snmp_data['eventSeverity']         = 1;
					$thold_snmp_data['eventStatus']           = 1;
					$thold_snmp_data['eventNotificationType'] = ST_NOTIFYRS+1;
					$thold_snmp_data['eventDeviceIp'] = gethostbyname($h['hostname']);

					thold_snmptrap($thold_snmp_data, SNMPAGENT_EVENT_SEVERITY_MEDIUM, $overwrite);
				}

				thold_log(array(
					'type'            => 2,
					'time'            => time(),
					'host_id'         => $thold_data['host_id'],
					'local_graph_id'  => $thold_data['local_graph_id'],
					'threshold_id'    => $thold_data['id'],
					'threshold_value' => '',
					'current'         => $thold_data['lastread'],
					'status'          => ST_NOTIFYRS,
					'description'     => $subject,
					'emails'          => $alert_emails)
				);

				db_execute_prepared('UPDATE thold_data
					SET thold_alert=0,
					thold_warning_fail_count = ?,
					thold_fail_count = ?
					WHERE id = ?',
					array($warning_failures, $failures, $thold_data['id']));
			} else {
				db_execute_prepared('UPDATE thold_data
					SET thold_fail_count = ?,
					thold_warning_fail_count = ?
					WHERE id = ?',
					array($failures, $warning_failures, $thold_data['id']));
			}
		}

		break;
`

**Comment by netniV** [comment] 2018-04-12 14:54
I've read over it briefly now and I think there is room for improvement.  I was actually in the process of refining the way that the breaches are done because there are some other parts that could be streamlined.  If I have the file with your comments in it, I can read it better though so could you do me a favour and attach that as a file as well?

**Comment by tddcacti** [comment] 2018-04-12 15:41
Sounds good, thanks.  I've uploaded the file here (just added a .txt extension since .php is not allowed)

[thold_functions_issue174.php.txt](https://github.com/Cacti/plugin_thold/files/1903907/thold_functions_issue174.php.txt)

**Comment by netniV** [comment] 2018-09-20 20:02
OK so I eventually got around to saving your file to my local repo and see what the differences are.  I can see quite a few changes between ours and you version.  Since the code has moved on quite a bit, are you using git ?

If so, you can do the following:

```
git remote add upstream https://github.com/cacti/plugin_thold/
git fetch upstream
git rebase upstream/develop
```
This should roll back your changes to the common ones, then apply your changes on to of our latest.  That way I'm not trying to unpick the differences that are purely because we've changed things (not you).

**Comment by netniV** [comment] 2018-10-17 11:00
Hi @tddcacti, 

Have you managed to rebase your work against the current develop branch?  Your comments make sense in the first part (I've been considering de-duping a lot of that code because it's crazy repeated).  But I wanted to review your other suggestions first to make sure I wasn't missing anything else.

**Comment by netniV** [comment] 2018-10-17 11:02
Additionally the undefined local_data_id issue should now be resolved as I corrected a number of issues already regarding how THold was locating the data source item.  So that should be resolved too.

**Comment by tddcacti** [comment] 2018-10-18 17:15
@netniV Thanks for following up on this.  I saw your note from a few weeks ago, but I haven't been able to make time to do the things you asked for--but I have this on my to-do list and hope to get to it soon, I will let you know what I find.

**Comment by TheWitness** [comment] 2018-12-28 19:35
I suggest you test using the latest version.  See the change log for important information.  This change required Cacti 1.2 in order to work.  See the change log below:

https://github.com/Cacti/plugin_thold/commit/0ad5286c970b90dbaac68a74ba910665853e2e71

**Comment by TheWitness** [comment] 2018-12-29 00:19
This is resolved in the latest develop.  Keeping open for a time.

**Closed as completed** 2019-02-02 00:31 UTC
Labels: resolved
